server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batchprocessing?allowPublicKeyRetrieval=true&useSSL=false
    username: ${username}
    password: ${password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  batch:
    initialize-schema: ALWAYS



## Spring Datasource Configuration
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#
## Spring H2 Console Configuration
#spring:
#  h2:
#    console:
#      enabled: true
#
## Spring Batch Configuration
#spring:
#  batch:
#    job:
#      enabled: false
